#!/bin/bash

echo "================================"
echo "🚀 Deploying Fee Fix to VPS"
echo "================================"
echo ""

# Step 1: Commit and push the fee fix
echo "📦 Step 1: Pushing fee fix to GitHub..."
cd /workspaces/saroyarsir
git add -A
git commit -m "Fix fee save issue - Map other_fee to others_fee database column"
git push origin main
echo "✅ Code pushed to GitHub"
echo ""

# Step 2: Create VPS deployment commands
echo "📋 Step 2: VPS Deployment Commands"
echo "================================"
echo ""
echo "Run these commands on your VPS (IP: 194.233.74.48):"
echo ""
echo "ssh root@194.233.74.48"
echo ""
echo "Then run:"
echo ""
echo "cd /var/www/saroyarsir"
echo "git pull origin main"
echo "sudo systemctl restart saro_vps"
echo "sudo systemctl status saro_vps"
echo ""
echo "# Check logs if there's an error:"
echo "sudo journalctl -u saro_vps -n 50 --no-pager"
echo ""
echo "================================"
echo "🔍 Fix Applied:"
echo "================================"
echo "✅ Fixed column name mismatch:"
echo "   - Database column: 'others_fee'"
echo "   - API uses: 'other_fee'"
echo "   - Now properly mapped in all routes"
echo ""
echo "✅ Updated files:"
echo "   - routes/fees.py (5 functions)"
echo "   - utils/response.py (serialize_fee)"
echo ""
echo "================================"
echo "📝 What was fixed:"
echo "================================"
echo "The error 'Saved 1 fee(s), 1 failed' was caused by"
echo "trying to save to a column named 'other_fee' when the"
echo "database column is actually named 'others_fee'."
echo ""
echo "All Fee creation/update functions now correctly use"
echo "'others_fee' for the database while keeping 'other_fee'"
echo "in the API for consistency."
echo "================================"
